//! Playbook — user-authored skill template that the runtime executes as a
//! one-shot prompt against the LLM.
//!
//! Distinct from `evo_core::Skill`, which is auto-generated by reflection
//! and tracks EWMA score / state. A Playbook is a hand-written YAML or
//! Markdown file with a `steps:` block of natural-language instructions
//! and a list of declared parameters. The runner loads the file, validates
//! required parameters, substitutes `{param}` placeholders in `steps`,
//! and pipes the rendered text to `task::run_one_shot` as the user input.
//!
//! Storage: `~/.evoclaw/playbooks/<id>.yaml` or `<id>.md` (frontmatter).

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;
use thiserror::Error;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaybookParam {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default = "default_required")]
    pub required: bool,
    #[serde(default)]
    pub example: Option<String>,
}

fn default_required() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Playbook {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub parameters: Vec<PlaybookParam>,
    pub steps: String,
    #[serde(default)]
    pub notes: Option<String>,
    /// Free-form scheduling hint (typically a launchd plist or crontab
    /// snippet) shown to the user when they run `evoclaw skill playbook-show`.
    /// EvoClaw itself does NOT execute this — the user installs it manually.
    /// Kept around so playbook authors have a documented place to record
    /// expected cadence alongside the rest of the spec.
    #[serde(default)]
    pub schedule: Option<String>,
}

#[derive(Debug, Error)]
pub enum PlaybookError {
    #[error("playbook not found: {0}")]
    NotFound(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("parse: {0}")]
    Parse(String),
    #[error("missing required parameter: {0}")]
    MissingParam(String),
}

impl Playbook {
    /// Load a playbook from a YAML (`*.yaml`/`*.yml`) or Markdown (`*.md`)
    /// file. Markdown files use a YAML frontmatter block delimited by `---`.
    pub async fn load(path: impl AsRef<Path>) -> Result<Self, PlaybookError> {
        let path = path.as_ref();
        let text = tokio::fs::read_to_string(path).await?;
        let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
        match ext {
            "md" => parse_md(&text),
            _ => parse_yaml(&text),
        }
    }

    /// Locate a playbook by id under `dir`. Tries `<id>.yaml`, `<id>.yml`,
    /// then `<id>.md` and returns the first match.
    pub async fn find(dir: impl AsRef<Path>, id: &str) -> Result<Self, PlaybookError> {
        let dir = dir.as_ref();
        for ext in ["yaml", "yml", "md"] {
            let p = dir.join(format!("{id}.{ext}"));
            if p.exists() {
                return Self::load(&p).await;
            }
        }
        Err(PlaybookError::NotFound(id.to_string()))
    }

    /// List every playbook discovered under `dir`. Bad files are skipped
    /// silently — they should not block valid playbooks from showing up.
    pub async fn list_dir(dir: impl AsRef<Path>) -> Result<Vec<Self>, PlaybookError> {
        let dir = dir.as_ref();
        let mut out = Vec::new();
        if !dir.exists() {
            return Ok(out);
        }
        let mut entries = tokio::fs::read_dir(dir).await?;
        while let Some(entry) = entries.next_entry().await? {
            let p = entry.path();
            let ext = p.extension().and_then(|s| s.to_str()).unwrap_or("");
            if !matches!(ext, "yaml" | "yml" | "md") {
                continue;
            }
            if let Ok(pb) = Self::load(&p).await {
                out.push(pb);
            }
        }
        out.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(out)
    }

    /// Substitute `{param}` placeholders in `steps` with values from
    /// `provided`. Required parameters with no value cause an error.
    /// Optional parameters with no value are substituted with an empty
    /// string.
    pub fn render_prompt(
        &self,
        provided: &HashMap<String, String>,
    ) -> Result<String, PlaybookError> {
        for p in &self.parameters {
            if p.required && !provided.contains_key(&p.name) {
                return Err(PlaybookError::MissingParam(p.name.clone()));
            }
        }
        let mut rendered = self.steps.clone();
        // Substitute declared parameters first (covers both required and
        // optional values) then sweep any leftover `{key}` placeholders
        // whose key matches a provided override (handy for ad-hoc params).
        let mut subs: HashMap<&str, &str> = HashMap::new();
        for p in &self.parameters {
            if let Some(v) = provided.get(&p.name) {
                subs.insert(p.name.as_str(), v.as_str());
            } else {
                subs.insert(p.name.as_str(), "");
            }
        }
        for (k, v) in provided {
            subs.entry(k.as_str()).or_insert(v.as_str());
        }
        for (k, v) in subs {
            rendered = rendered.replace(&format!("{{{k}}}"), v);
        }
        Ok(rendered)
    }
}

fn parse_yaml(text: &str) -> Result<Playbook, PlaybookError> {
    serde_yaml::from_str(text).map_err(|e| PlaybookError::Parse(e.to_string()))
}

fn parse_md(text: &str) -> Result<Playbook, PlaybookError> {
    let trimmed = text.trim_start_matches('\u{feff}');
    let body = trimmed
        .strip_prefix("---\n")
        .or_else(|| trimmed.strip_prefix("---\r\n"))
        .ok_or_else(|| PlaybookError::Parse("missing leading '---'".into()))?;
    let end = body
        .find("\n---\n")
        .or_else(|| body.find("\n---\r\n"))
        .or_else(|| body.find("\n---"))
        .ok_or_else(|| PlaybookError::Parse("missing closing '---'".into()))?;
    parse_yaml(&body[..end])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_yaml() -> &'static str {
        r#"
id: test
name: Test playbook
description: A test
parameters:
  - name: out_dir
    description: where to write
    example: "~/out"
  - name: dry_run
    description: skip side effects
    required: false
steps: |
  Write a digest into {out_dir}.
  dry_run = {dry_run}
notes: |
  optional notes
"#
    }

    #[test]
    fn parse_yaml_round_trip() {
        let pb = parse_yaml(sample_yaml()).unwrap();
        assert_eq!(pb.id, "test");
        assert_eq!(pb.parameters.len(), 2);
        assert!(pb.parameters[0].required);
        assert!(!pb.parameters[1].required);
    }

    #[test]
    fn parse_md_strips_frontmatter() {
        let md = format!("---\n{}\n---\n# Human notes\nIgnored.\n", sample_yaml());
        let pb = parse_md(&md).unwrap();
        assert_eq!(pb.id, "test");
    }

    #[test]
    fn render_substitutes_required_params() {
        let pb = parse_yaml(sample_yaml()).unwrap();
        let mut params = HashMap::new();
        params.insert("out_dir".into(), "/tmp/a".into());
        let out = pb.render_prompt(&params).unwrap();
        assert!(out.contains("/tmp/a"));
        assert!(!out.contains("{out_dir}"));
    }

    #[test]
    fn render_optional_param_defaults_to_empty() {
        let pb = parse_yaml(sample_yaml()).unwrap();
        let mut params = HashMap::new();
        params.insert("out_dir".into(), "/tmp/a".into());
        let out = pb.render_prompt(&params).unwrap();
        assert!(out.contains("dry_run = "));
        assert!(!out.contains("{dry_run}"));
    }

    #[test]
    fn render_missing_required_errors() {
        let pb = parse_yaml(sample_yaml()).unwrap();
        let params = HashMap::new();
        let err = pb.render_prompt(&params).unwrap_err();
        assert!(matches!(err, PlaybookError::MissingParam(_)));
    }

    #[test]
    fn parse_md_rejects_missing_closing_marker() {
        let bad = "---\nid: x\nname: y\nsteps: hi\n";
        assert!(parse_md(bad).is_err());
    }

    #[tokio::test]
    async fn find_locates_by_id_across_extensions() {
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("evo-playbook-{stamp}"));
        tokio::fs::create_dir_all(&dir).await.unwrap();
        tokio::fs::write(dir.join("p1.yaml"), sample_yaml())
            .await
            .unwrap();
        let pb = Playbook::find(&dir, "p1").await.unwrap();
        assert_eq!(pb.id, "test");
    }

    #[tokio::test]
    async fn list_dir_returns_sorted() {
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("evo-playbook-list-{stamp}"));
        tokio::fs::create_dir_all(&dir).await.unwrap();
        let yaml1 = sample_yaml().replace("id: test", "id: zeta");
        let yaml2 = sample_yaml().replace("id: test", "id: alpha");
        tokio::fs::write(dir.join("zeta.yaml"), yaml1)
            .await
            .unwrap();
        tokio::fs::write(dir.join("alpha.yaml"), yaml2)
            .await
            .unwrap();
        let pbs = Playbook::list_dir(&dir).await.unwrap();
        assert_eq!(pbs.len(), 2);
        assert_eq!(pbs[0].id, "alpha");
        assert_eq!(pbs[1].id, "zeta");
    }
}
